purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6875
  brandStrength: 0.5053763
  lightness: 0.5
  brandColors:
    - '#FFFFFF'
    - '#020202'
    - '#656565'
    - '#A1A1A1'
    - '#444444'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
name: Audere
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.37256
layout_spectrum: 1
