name: Audere
favicon: null
layout_spectrum: 0.6766128262970597
typography_spectrum: 0.36841919575817883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5860479264520109
  lightness: 0.4802956653293222
  saturation: 0.7114033058751374
  rhythmicContrast: 0.5887302185874432
purpose: []
